### ISSUE TITLE
Some minor things with latest Usurper

### ISSUE THREAD

**Issue by stack-fault** [rickparrish/Usurper#14]
- Many places in the game, the string are being sent with an extra CR, breaking the 
display of many ANSIs and such. But it's not everywhere. I thought it might be some files having DOS CR/LF but it comes from the binary apparently.

- You can't just hit enter on several prompts where it should be allowed, two occurrences below as an example:
  o Attacking the first enemy in the dungeons
  o Abort selling all your items

I am using the latest Linux binary.

**Comment by rickparrish** [comment]
What BBS software are you using, and have you tried with the -X command-line parameter?  It's been a long time since I worked on Usurper, but another Issue mentioned that parameter being added for STDIO mode to help with the extra CR issue.

And can you take a screenshot of any screens where hitting ENTER should work but doesn't?  Having not worked on it in so long I don't recall where to find stuff, so a screenshot showing some text I can grep for should help.

**Comment by CraigEMP** [comment]
Here's a spot where pressing [Enter] should pick the first monster when "Fighting to Death", but it does nothing.  Instead it makes you select the number.

![image](https://user-images.githubusercontent.com/12660452/78259068-2cad6b80-74ca-11ea-8d94-5efffc7cbdc9.png)

**Comment by rickparrish** [comment]
Had a quick look, and I think it's related to me switching from DDPlus to my own doorkit -- there's a lot of TODO comments in there indicating I mapped the DDPlus call to what I thought the closest match was in my doorkit, but no testing was done to confirm exact matching behaviour.

And I know for sure my line input function wasn't exact matching behaviour, because it doesn't accept empty input, so that explains why hitting enter for the first monster isn't working.

I'll try switching back to DDPlus in the near future to confirm.  I don't recall why I switched in the first place though...it may have fixed some issues but introduced ones like this, so then going back to DDPlus would fix these issues but reintroduce old issues.

**Comment by rickparrish** [comment]
Switched back to DDPlus on this branch:
https://github.com/rickparrish/Usurper/tree/DDPlus

New Win32 binaries are included, but I don't have a VM setup to build for Linux so those will have to be built from source.

**Comment by CraigEMP** [comment]
> New Win32 binaries are included, but I don't have a VM setup to build for Linux so those will have to be built from source.

I'm finally going to test over the upcoming weekend.

Two questions:

1. There are two sets of Windows binaries: *.exe and *32.exe.  I assume they're _both_ Win32, but only the USURPER.exe seems to have been compiled recently.  What is the difference, and which should be used?

2. When compiling the DDPlus branch, Lazarus gives the error: "DDFOSSIL.PAS(60,3) Fatal: Cannot find Comm used by ddfossil".  This is a fresh Lazarus install.  I assume I'm missing a dependency - how can I fix?

**Comment by CraigEMP** [comment]
I can confirm the DDPlus build fixes the issues.  Pressing [enter] now auto-selects the default option when it should.
